name: Make release

on:
    release:
        types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '22'
      - run: npm install 
      - run: npm install -g @vscode/vsce
      - run: vsce package
      - name: Upload vsix to release
        uses: AButler/upload-release-assets@v1.0
        with:
            files: '*.vsix'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
